#!/bin/bash

# Script to go to a higher ghc version
#
# Procedure
# Remove all upper bound in the cabal file
# Run this script ./newghc
# Add the new upper bounds into the cabal file

rm -rf .cabal-sandbox
cabal sandbox init
cabal install --only-dependencies
cabal install tasty
cabal install tasty-hunit
cabal install tasty-quickcheck
