# Stack file for swissgeo
resolver: lts-16.9

packages:
- '.'

# Extra packages from Hackage
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []