# Stack file for swissgeo
resolver: lts-10.0

packages:
- '.'

# Extra packages from Hackage
extra-deps: 
- cabal-test-quickcheck-0.1.8.1

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

